dist: trusty
sudo: false
language: generic

cache:
  directories:
    /home/travis/build/stevehoover/warp-v/warpv_formal/env

before_install:
  - cd ..
install:
  # If env is not provided by the cache, build it.
  - ( cd warp-v/warpv_formal && if [ ! -e env ]; then ./make_env.sh )
  # Clone riscv-formal.
  - git clone https://github.com/cliffordwolf/riscv-formal.git && pushd riscv-formal && git checkout 51076e93d70648cf813ef00d7e4cd93b94ea55f5
  
before_script:
  - cp -rf warp-v/warpv_formal riscv-formal/cores/ && cd riscv-formal/cores/warpv_formal
script:
  # Run riscv-formal for WARP-V.
  - PATH=/home/travis/build/stevehoover/warp-v/warpv_formal/env/bin:$PATH bash -c 'echo PATH=$PATH && make genchecks && make verif -j4'
after_success:
after_failure:
  # Upload files for debug.
  - echo "Uploading up to 4 failure traces for debug" && for FILE in `ls /home/travis/build/stevehoover/riscv-formal/cores/warpv_formal/checks/*/FAIL | head -n 4`; do curl --upload-file `echo $FILE | sed s/FAIL$//`engine_0/trace.vcd https://transfer.sh/`echo $FILE | sed 's/^.*\/\([^\/]*\)\/FAIL$/\1/'`_trace.vcd && echo; done
after_script:
  # Report a message if we didn't use the latest commit of yosys.
  - if cmp -s yosys_latest_commit_id.txt env/yosys_commit_id.txt; then echo '******** Using the following cached yosys (https://github.com/cliffordwolf/yosys.git) commit ID which is not the latest. Consider clearing Travis cache. **********' && cat env/yosys_commit_id.txt && echo '**********'; fi
  # Report a message if we didn't use the latest commit of SymbiYosys.
  - if cmp -s SymbiYosys_latest_commit_id.txt env/SymbiYosys_commit_id.txt; then echo '******** Using the following cached SymbiYosys (https://github.com/cliffordwolf/SymbiYosys) commit ID which is not the latest. Consider clearing Travis cache. **********' && cat env/SymbiYosys_commit_id.txt && echo '**********'; fi
